Proyecto2-main/HDP115/config/urls.py
from django.contrib import admin
from django.urls import path
from flujoMigratorio.views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from flujoMigratorio import views 
from django.contrib.auth.views import LoginView,LogoutView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index.as_view(), name='home'),
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('registrarPersona/',registrarPersona.as_view(), name='registrarPersona'),
    path('buscarPersonaEntrada/',indexEntrarPersona.as_view(),name='buscarPersonaEntrada'),
    path('registrarEntradaPersona/<str:idp>/',entradaPersona.as_view(),name='registrarEntradaPersona'),
    path('indexPersonas/',indexPersonas.as_view(),name='indexPersonas'),
    path('agregarAlarma/<str:idp>/',agregarAlarma.as_view(),name='agregarAlarma'),
    path('buscarPersonaSalida/',indexSalirPersona.as_view(),name='buscarPersonaSalida'),
    path('registrarSalidaPersona/<str:idp>/',salidaPersona.as_view(),name='registrarSalidaPersona')
]

Proyecto2-main/HDP115/flujoMigratorio/models.py
from django.db import models

nacional_extranjero= [
    (1, 'Nacional'),
    (2, 'Extranjero')
]
tipo_Documento=[
    (1, 'DUI'),
    (2, 'Pasaporte')
]
estado_actual=[
    (1, 'Fuera del Paìs'),
    (2, 'En el Pais')
]
tipo_alarma = [
    (1, 'Alarma 1'),
    (2, 'Alarma 2')
]
class persona(models.Model):
    idPersona = models.AutoField(primary_key=True)
    pasaporte = models.CharField(max_length=9, unique=True, default="", null=True,blank=True)
    dui = models.CharField(max_length=10, unique=True, default="", null=True,blank=True)
    nombre = models.CharField(max_length= 50, default="")
    apellido = models.CharField(max_length=50, default="")
    tipoDocumento = models.IntegerField(
        blank=True,
        choices=tipo_Documento
    ) 
    nacionalidad = models.IntegerField(
        blank=True,
        choices=nacional_extranjero
    ) 
    estado = models.IntegerField(
        blank=True,
        choices=estado_actual
    )
    

class Entrada(models.Model):
    persona = models.ForeignKey('persona', on_delete=models.CASCADE, null=True)
    fechaIngreso = models.DateField()
    TiempoPermanencia = models.CharField(max_length=10, default="",blank=True)
    paisOrigen = models.CharField(max_length=10, default="")

class Salida(models.Model):
    persona = models.ForeignKey('persona', on_delete=models.CASCADE, null=True)
    fechaSalida = models.DateField()
    TiempoPermanencia = models.CharField(max_length=10, default="",blank=True)
    paisDestino = models.CharField(max_length=10, default="")

class Alarma(models.Model):
    persona = models.ForeignKey('persona', on_delete=models.CASCADE, null=True)
    tipoAlerta = models.IntegerField(
        blank=True,
        choices=tipo_alarma
    )
    descripcion = models.TextField(max_length=200,blank = True, default="")

Proyecto2-main/HDP115/templates/agregarAlarma.html
{% extends 'index.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %} 
{% endblock %}



{% block content %} 
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Agregar Alarma</h3>
                </div>
                <div class="panel-body">
                    <form id = "formulario" role="form" action="." method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <p class="label-form">Nombre de la Persona: </p>
                                        {{personas.nombre}} {{personas.apellido}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">Tipo de Alarma</p>
                                        {{form.tipoAlerta}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">Descripcion</p>
                                        {{form.descripcion|add_class:'form-control'|attr:'rows:3' |attr:'colm:40'|attr:'autocomplete:off'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row">
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-primary btn-block"> Agregar </button>
                            </div>
                            <div class="col-md-2">
                                <a class="btn btn-danger btn-block" href="javascript:history.back()"> Cancelar </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



{% block scripts %}
{% endblock %}

Proyecto2-main/HDP115/templates/buscarEntrada.html
{% extends 'index.html' %}
{% load static %}

{% block head %} 
{% endblock %}



{% block content %} 

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-panel panel panel-default">
                
                <div class="panel-heading">
                    <h3 class="panel-title">Buscar Personas</h3>
                </div>
                <form class="d-flex" role="search" method="GET">
                    <input class="form-control me-2" type="search" name="buscar" value="" autocomplete='off' placeholder="Buscar..." aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
                <div class="panel-body">
                    
                    <form id = "formulario" role="form" action="." method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <div class="row">
                                <div class="col-md-6">
                                    <table class="table">
                                        <thead>
                                            <th>Documento</th>
                                            <th>Nombre</th>
                                            <th>Apellido</th>
                                            <th>OPCIONES</th>
                                        </thead>
                                        <tbody>

                                            {% for p in personas%}
                                            <tr>
                                                {% if p.estado == 1 %}
                                                    
                                                    {% if p.pasaporte == Null %}
                                                        <td>{{p.dui}}</td>
                                                    {% endif %}
                                                    {% if p.dui == Null %}
                                                        <td>{{p.pasaporte}}</td>
                                                    {% endif %}
                                                    <td>{{p.nombre}}</td>
                                                    <td>{{p.apellido}}</td>
                                                    
                                                    <td><a class="btn btn-secondary"href="{% url 'registrarEntradaPersona' p.idPersona %}">Registrar Entrada </a></td>
                                                {% endif %}
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row">
                            <div class="col-md-2">
                                <a class="btn btn-danger btn-block" href="{% url 'home' %}"> Cancelar </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



{% block scripts %}
<!-- DataTables JavaScript -->
<script src="{% static 'js/dataTables/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'js/dataTables/dataTables.bootstrap.min.js'%}"></script>
<script type= application/javascript>
    {%if messages%}
        var msg = '';
        var msg1 = '';
        {%for message in messages%}
        {% if 'error' in message.tags %}
            msg += '{{ message }}\n';
          {% endif %}
        {% endfor %}
        if(msg != ''){
        Swal.fire({
            icon: 'error',
            text: msg,
            //footer: '<a href="">Why do I have this issue?</a>'
          })
        }
        {%for message in messages%}
        {% if 'success' in message.tags %}
            msg1 += '{{ message }}\n';
          {% endif %}
        {% endfor %}
        if(msg1 != ''){
            Swal.fire({
                icon: 'success',
                text: msg1,
              })
        }
    {% endif %} 
  </script>
{% endblock %}

Proyecto2-main/HDP115/templates/buscarSalida.html
{% extends 'index.html' %}
{% load static %}

{% block head %} 
{% endblock %}



{% block content %} 

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-panel panel panel-default">
                
                <div class="panel-heading">
                    <h3 class="panel-title">Buscar Personas</h3>
                </div>
                <form class="d-flex" role="search" method="GET">
                    <input class="form-control me-2" type="search" name="buscar" value="" autocomplete='off' placeholder="Buscar..." aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
                <div class="panel-body">
                    
                    <form id = "formulario" role="form" action="." method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <div class="row">
                                <div class="col-md-6">
                                    <table class="table">
                                        <thead>
                                            <th>Documento</th>
                                            <th>Nombre</th>
                                            <th>Apellido</th>
                                            <th>OPCIONES</th>
                                        </thead>
                                        <tbody>

                                            {% for p in personas%}
                                            <tr>
                                                {% if p.estado == 2 %}
                                                    
                                                    {% if p.pasaporte == Null %}
                                                        <td>{{p.dui}}</td>
                                                    {% endif %}
                                                    {% if p.dui == Null %}
                                                        <td>{{p.pasaporte}}</td>
                                                    {% endif %}
                                                    <td>{{p.nombre}}</td>
                                                    <td>{{p.apellido}}</td>
                                                    
                                                    <td><a class="btn btn-secondary"href="{% url 'registrarSalidaPersona' p.idPersona %}">Registrar Salida</a></td>
                                                {% endif %}
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row">
                            <div class="col-md-2">
                                <a class="btn btn-danger btn-block" href="{% url 'home' %}"> Cancelar </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



{% block scripts %}
<!-- DataTables JavaScript -->
<script src="{% static 'js/dataTables/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'js/dataTables/dataTables.bootstrap.min.js'%}"></script>
<script type= application/javascript>
    {%if messages%}
        var msg = '';
        var msg1 = '';
        {%for message in messages%}
        {% if 'error' in message.tags %}
            msg += '{{ message }}\n';
          {% endif %}
        {% endfor %}
        if(msg != ''){
        Swal.fire({
            icon: 'error',
            text: msg,
            //footer: '<a href="">Why do I have this issue?</a>'
          })
        }
        {%for message in messages%}
        {% if 'success' in message.tags %}
            msg1 += '{{ message }}\n';
          {% endif %}
        {% endfor %}
        if(msg1 != ''){
            Swal.fire({
                icon: 'success',
                text: msg1,
              })
        }
    {% endif %} 
  </script>
{% endblock %}

Proyecto2-main/HDP115/templates/entradaPersona.html
{% extends 'index.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %} 
{% endblock %}



{% block content %} 
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Agregar Entrada de Personas al Paìs</h3>
                </div>
                <div class="panel-body">
                    <form id = "formulario" role="form" action="." method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <p class="label-form">Nombre de la Persona: </p>
                                            {{personas.nombre}} {{personas.apellido}}
                                            <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                        </div>
                                        <p class="label-form">Fecha de ingreso al paìs</p>
                                        {{form.fechaIngreso|add_class:'form-control'|attr:'autocomplete:off'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">Tiempo de Permanencia</p>
                                        {{form.TiempoPermanencia|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Ingrese el tiempo en meses de permanencia en el Paìs'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">Paìs Origen</p>
                                        {{form.paisOrigen|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Ingrese el paìs de Origen'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row">
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-primary btn-block"> Agregar </button>
                            </div>
                            <div class="col-md-2">
                                <a class="btn btn-danger btn-block" href="{% url 'buscarPersonaEntrada' %}"> Cancelar </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



{% block scripts %}
{% endblock %}

Proyecto2-main/HDP115/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Flujo Migratorio</title>
      <!-- Otros estilos -->
      <link href="{% static 'css/style.css'%}" rel="stylesheet"  type="text/css">
      
      <!-- MetisMenu CSS -->
      <link rel="stylesheet" href="{% static 'css/metisMenu.min.css'%}" type="text/css">
      <!-- Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/startmin.css'%}" type="text/css">
      <!-- Custom Fonts -->
      <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}" type="text/css">
      <!-- Iconos -->
      <link rel="stylesheet" href="{% static 'css/all.min.css'%}" type="text/css">
      {% block head %} {% endblock %}
    </head> 
    <body>    
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
        <div class="container-fluid">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">
          <img src="{% static 'img/logo.PNG' %}" width="120px" height="70px"/>
          </a>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto mb-0 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Gestionar Personas</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'registrarPersona' %}">Registrar Persona</a></li>
                  <li><a class="dropdown-item" href="{% url 'indexPersonas' %}">Consultar Personas</a></li>
                </ul>           
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'buscarPersonaEntrada' %}">Registrar Entrada</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'buscarPersonaSalida' %}">Registrar Salida</a>
              </li>
              <li class="nav-item">
                <a class="nav-link"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                <img src="{% static 'img/cerrarIcono.png' %}"width="50px" height="50px">
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div  class="content">
        {% block content %} 
        {% endblock content %}
      </div>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- Bootstrap Core JavaScript -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Metis Menu Plugin JavaScript -->
      <script src="{% static 'js/metisMenu.min.js'%}"></script>
      <!-- Custom Theme JavaScript -->
      <script src="{% static 'js/startmin.js'%}"></script>
      <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>  
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js"></script>
      <!-- main -->
      <script src="{% static 'js/main.js'%}"></script>
     
    </body>
</html>
{% block scripts %}
<!-- DataTables JavaScript -->
<script src="{% static 'js/dataTables/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'js/dataTables/dataTables.bootstrap.min.js'%}"></script>
<script type= application/javascript>
    {%if messages%}
        var msg = '';
        var msg1 = '';
        {%for message in messages%}
        {% if 'error' in message.tags %}
            msg += '{{ message }}\n';
          {% endif %}
        {% endfor %}
        if(msg != ''){
        Swal.fire({
            icon: 'error',
            text: msg,
            //footer: '<a href="">Why do I have this issue?</a>'
          })
        }
        {%for message in messages%}
        {% if 'success' in message.tags %}
            msg1 += '{{ message }}\n';
          {% endif %}
        {% endfor %}
        if(msg1 != ''){
            Swal.fire({
                icon: 'success',
                text: msg1,
              })
        }
    {% endif %} 
  </script>
{% endblock %}

Proyecto2-main/HDP115/templates/ingresarPersonas.html
{% extends 'index.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %} 

{% endblock %}

{% block content %} 

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Agregar Personas</h3>
                </div>
                <div class="panel-body">
                    <form id = "formulario" role="form" action="." method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <p class="label-form">{{form.nombre.label}}</p>
                                        {{form.nombre|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">{{form.apellido.label}}</p>
                                        {{form.apellido|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">{{form.tipoDocumento.label}}</p>
                                        {{form.tipoDocumento}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div id="pasaporte" class="form-group oculto" >
                                        <p class="label-form">{{form.pasaporte.label}}</p>
                                        {{form.pasaporte|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div id="dui" class="form-group oculto" >
                                        <p class="label-form">{{form.dui.label}}</p>
                                        {{form.dui|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">{{form.nacionalidad.label}}</p>
                                        {{form.nacionalidad}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">{{form.estado.label}}</p>
                                        {{form.estado}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row">
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-primary btn-block"> Agregar </button>
                            </div>
                            <div class="col-md-2">
                                <a class="btn btn-danger btn-block" href="{% url 'home' %}"> Cancelar </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script type= application/javascript>

$('#id_tipoDocumento').on('change',function(){
        var selectValor = $(this).val();
        if (selectValor == '1') {
            $('#dui').removeClass('oculto');
            $('#pasaporte').addClass('oculto');
        }else if(selectValor == '2'){
            $('#pasaporte').removeClass('oculto');  
            $('#dui').addClass('oculto'); 
        }else{
            $('#pasaporte').addClass('oculto');
            $('#dui').addClass('oculto');
        }
    });
    $('form').submit(function(event) { 
        if($('#id_tipoDocumento').val() == '1') {
            if($('#id_dui').val() == '') {
                Swal.fire({
                    icon: 'error',
                    text: 'Debe el numero de DUI',
                  })
                return false;
            }
        }
        if($('#id_tipoDocumento').val() == '2') {
            if($('#id_pasaporte').val() == '') {
                Swal.fire({
                    icon: 'error',
                    text: 'Debe el pasaporte',
                  })
                return false;
            }
        }
    
    });

</script>
{% endblock %}

Proyecto2-main/HDP115/templates/login.html
<div>
    <center>
        <h1>Iniciar sesión</h1>
        <form class="container-fluid" method="post">
                {% csrf_token %}
                {{ form.as_p }}
            <button class="btn btn-primary" type="submit">INICIAR SESION</button>
        </form>
    </center>
</div>

Proyecto2-main/HDP115/templates/salidaPersona.html
{% extends 'index.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %} 
{% endblock %}



{% block content %} 
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Agregar Salida de Personas al Paìs</h3>
                </div>
                <div class="panel-body">
                    <form id = "formulario" role="form" action="." method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <p class="label-form">Nombre de la Persona: </p>
                                            {{personas.nombre}} {{personas.apellido}}
                                            <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                        </div>
                                        <p class="label-form">Fecha de Salida al paìs</p>
                                        {{form.fechaSalida|add_class:'form-control'|attr:'autocomplete:off'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">Tiempo de Permanencia</p>
                                        {{form.TiempoPermanencia|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Ingrese el tiempo en meses de permanencia en el Paìs'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                    <div class="form-group">
                                        <p class="label-form">Paìs Origen</p>
                                        {{form.paisDestino|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Ingrese el paìs de Origen'}}
                                        <div class ="help-block"><p class="text-muted label-help-form"></p></div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row">
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-primary btn-block"> Agregar </button>
                            </div>
                            <div class="col-md-2">
                                <a class="btn btn-danger btn-block" href="{% url 'buscarPersonaEntrada' %}"> Cancelar </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



{% block scripts %}
{% endblock %}